Slightly trickier: you may need to combine two or more methods to get the right answer

In [1]:
#22
import pandas as pd
import numpy as np
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})

In [2]:
df

    A
0   1
1   2
2   2
3   3
4   4
5   5
6   5
7   5
8   6
9   7
10  7

In [3]:
df.duplicated().sum()

np.int64(4)

In [4]:
df.drop_duplicates(keep = "first", inplace = True )

In [5]:
df

   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

In [6]:
df = pd.DataFrame(np.random.random(size=(5, 3))) 
df

df = df.apply(lambda x: x - x.mean(),axis =1)
df

          0         1         2
0 -0.232944  0.214202  0.018742
1 -0.201548  0.497600 -0.296052
2 -0.008044 -0.181952  0.189996
3 -0.122827 -0.157107  0.279934
4 -0.237479  0.131773  0.105705

In [7]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))

In [8]:
df

,a,b,c,d,e,f,g,h,i,j
0,0.068234,0.957173,0.115476,0.081256,0.990695,0.201146,0.414612,0.619143,0.394780,0.628536
1,0.599167,0.815682,0.585446,0.383174,0.816211,0.792142,0.841942,0.881624,0.231669,0.482027
2,0.360372,0.336819,0.023504,0.370352,0.996911,0.795586,0.886956,0.366351,0.155783,0.149277
3,0.092255,0.044784,0.339424,0.623393,0.001228,0.626482,0.734170,0.535401,0.799499,0.036890
4,0.875820,0.368832,0.762180,0.277324,0.479192,0.317216,0.555855,0.251878,0.141879,0.022318

In [9]:
df

,a,b,c,d,e,f,g,h,i,j
0,0.068234,0.957173,0.115476,0.081256,0.990695,0.201146,0.414612,0.619143,0.394780,0.628536
1,0.599167,0.815682,0.585446,0.383174,0.816211,0.792142,0.841942,0.881624,0.231669,0.482027
2,0.360372,0.336819,0.023504,0.370352,0.996911,0.795586,0.886956,0.366351,0.155783,0.149277
3,0.092255,0.044784,0.339424,0.623393,0.001228,0.626482,0.734170,0.535401,0.799499,0.036890
4,0.875820,0.368832,0.762180,0.277324,0.479192,0.317216,0.555855,0.251878,0.141879,0.022318

In [10]:
small = df.sum().tail(1)
for x, y in small.items():
  print(f"The smallest sum is of {x}")

The smallest sum is of j

In [11]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))

In [12]:
unique = df.drop_duplicates()
print(f"Unique values:{len(unique)}")

Unique values:4

PRACTICING DATA CLEANING

In [13]:
data = pd.read_csv("./Data/anime.csv")
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [14]:
data

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [15]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [16]:
data.isnull().sum()

Rank     0
Title    0
Score    0
dtype: int64

In [17]:
def sep(title):
  data = ""
  check = False
  for x in title:
    if x == "(":
      check = True 
    if check == True:
      data +=x
    if x == ")":
      check = False
      return data

data["Episodes"] = data["Title"].apply(sep).str.strip("()")

In [18]:
data

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04   51 eps
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04    1 eps
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04  148 eps
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04   13 eps
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03   13 eps
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03    2 eps
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02  110 eps
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99   13 eps
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99   13 eps
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98   12 eps
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94  201 eps
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94    1 eps
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93   22 eps
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93   24 eps
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91   25 eps
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91    1 eps
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89    1 eps
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88    7 eps
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88   14 eps
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87   74 eps
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84    1 eps
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84    1 eps
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83   12 eps
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83    1 eps
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82   24 eps
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82   23 eps
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81   12 eps
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81   26 eps
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80   13 eps
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80   16 eps
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79   11 eps
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79    1 eps
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79   11 eps
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78   10 eps
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78    1 eps
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77   26 eps
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77   12 eps
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76   75 eps
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75   26 eps
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75   26 eps
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74   24 eps
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73   10 eps
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72   12 eps
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71   12 eps
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71    4 eps

In [19]:
data.loc[0,["Title"]]

Title    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: 0, dtype: str

In [20]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

In [21]:
df

      a   b     c     d     e     f     g     h     i     j
0  0.04 NaN   NaN  0.25   NaN  0.43  0.71  0.51   NaN   NaN
1   NaN NaN   NaN  0.04  0.76   NaN   NaN  0.67  0.76  0.16
2   NaN NaN  0.50   NaN  0.31  0.40   NaN   NaN  0.24  0.01
3  0.49 NaN   NaN  0.62  0.73  0.26  0.85   NaN   NaN   NaN
4   NaN NaN  0.41   NaN  0.05   NaN  0.61   NaN  0.48  0.68

In [22]:
df.isna()

       a     b      c      d      e      f      g      h      i      j
0  False  True   True  False   True  False  False  False   True   True
1   True  True   True  False  False   True   True  False  False  False
2   True  True  False   True  False  False   True   True  False  False
3  False  True   True  False  False  False  False   True   True   True
4   True  True  False   True  False   True  False   True  False  False

In [23]:
def check(column):
  count = 0
  for x in range(len(column)):
    if column[x] == np.nan:
      count+= 1
  return count

name = df.apply(check, axis = 0)

In [24]:
data = {
    "order_id":   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "category":   ["Electronics", "Clothing", "Electronics", "Home", "Clothing",
                    "Electronics", "Home", "Clothing", "Home", "Electronics",
                    "Clothing", "Home"],
    "region":     ["East", "East", "West", "West", "East",
                    "West", "East", "West", "West", "East",
                    "West", "East"],
    "sales":      [250, 80, 400, 150, 60, 300, 200, 90, 175, 500, 110, 220],
    "quantity":   [2, 1, 3, 2, 1, 2, 4, 1, 3, 5, 2, 3],
    "rep":        ["Ana", "Ben", "Ana", "Cara", "Ben",
                    "Ana", "Cara", "Ben", "Cara", "Ana",
                    "Ben", "Cara"],
}

In [37]:
df = pd.DataFrame(data)

In [38]:
df

    order_id     category region  sales  quantity   rep
0          1  Electronics   East    250         2   Ana
1          2     Clothing   East     80         1   Ben
2          3  Electronics   West    400         3   Ana
3          4         Home   West    150         2  Cara
4          5     Clothing   East     60         1   Ben
5          6  Electronics   West    300         2   Ana
6          7         Home   East    200         4  Cara
7          8     Clothing   West     90         1   Ben
8          9         Home   West    175         3  Cara
9         10  Electronics   East    500         5   Ana
10        11     Clothing   West    110         2   Ben
11        12         Home   East    220         3  Cara

In [39]:
df.groupby("category")["sales"].sum()

category
Clothing        340
Electronics    1450
Home            745
Name: sales, dtype: int64

In [ ]:
df.groupby("region").agg({"sales":["max","mean"]})

       sales
         max        mean
region
East     500  218.333333
West     400  204.166667

In [54]:
df.groupby("category")[["sales","quantity"]].sum()

             sales  quantity
category
Clothing       340         5
Electronics   1450        12
Home           745        12

In [42]:
df

    order_id     category region  sales  quantity   rep
0          1  Electronics   East    250         2   Ana
1          2     Clothing   East     80         1   Ben
2          3  Electronics   West    400         3   Ana
3          4         Home   West    150         2  Cara
4          5     Clothing   East     60         1   Ben
5          6  Electronics   West    300         2   Ana
6          7         Home   East    200         4  Cara
7          8     Clothing   West     90         1   Ben
8          9         Home   West    175         3  Cara
9         10  Electronics   East    500         5   Ana
10        11     Clothing   West    110         2   Ben
11        12         Home   East    220         3  Cara

0     False
1     False
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
dtype: bool

In [57]:
df.groupby("region").agg({"sales":"sum", "quantity":"mean"})

        sales  quantity
region
East     1310  2.666667
West     1225  2.166667

In [59]:
df.groupby(by =["category", "region"])["sales"].sum().sort_values(ascending=False)

category     region
Electronics  East      750
             West      700
Home         East      420
             West      325
Clothing     West      200
             East      140
Name: sales, dtype: int64

In [66]:
df.groupby(by =["category", "region"])["sales"].sum().reset_index()

      category region  sales
0     Clothing   East    140
1     Clothing   West    200
2  Electronics   East    750
3  Electronics   West    700
4         Home   East    420
5         Home   West    325

In [69]:
df.groupby("rep").aggregate({"sales":["count","mean"]})

     sales
     count    mean
rep
Ana      4  362.50
Ben      4   85.00
Cara     4  186.25

In [67]:
df

    order_id     category region  sales  quantity   rep
0          1  Electronics   East    250         2   Ana
1          2     Clothing   East     80         1   Ben
2          3  Electronics   West    400         3   Ana
3          4         Home   West    150         2  Cara
4          5     Clothing   East     60         1   Ben
5          6  Electronics   West    300         2   Ana
6          7         Home   East    200         4  Cara
7          8     Clothing   West     90         1   Ben
8          9         Home   West    175         3  Cara
9         10  Electronics   East    500         5   Ana
10        11     Clothing   West    110         2   Ben
11        12         Home   East    220         3  Cara

In [75]:
df.groupby("category")["sales"].sum().sort_values(ascending=False)

category
Electronics    1450
Home            745
Clothing        340
Name: sales, dtype: int64

In [79]:
df.groupby("category").sum(numeric_only=True)

             order_id  sales  quantity
category
Clothing           26    340         5
Electronics        20   1450        12
Home               32    745        12

In [85]:
df.groupby("category").filter(lambda x: x["sales"].sum() > 500)

    order_id     category region  sales  quantity   rep
0          1  Electronics   East    250         2   Ana
2          3  Electronics   West    400         3   Ana
3          4         Home   West    150         2  Cara
5          6  Electronics   West    300         2   Ana
6          7         Home   East    200         4  Cara
8          9         Home   West    175         3  Cara
9         10  Electronics   East    500         5   Ana
11        12         Home   East    220         3  Cara

In [87]:
df.groupby("category").apply(lambda x: x["sales"].max() - x["sales"].min()).sort_values(ascending=False)

category
Electronics    250
Home            70
Clothing        50
dtype: int64

In [89]:
df.groupby("category")["sales"].agg(["min","max"])

             min  max
category
Clothing      60  110
Electronics  250  500
Home         150  220