In [2]:
import pandas as pd
import numpy as np

In [3]:
details = {"Name":["Mustufa","Ahmed","Ibrahim"], "Age": [21, 19, 12], "School": ["ABA","AUS", "ASD"]}
df = pd.DataFrame(details, index = ["Person 1","Person 2","Person 3"])

In [4]:
Edu_details = np.array([["Mustufa","Ahmed","Ibrahim"],[21, 19, 12],["ABA","AUS", "ASD"]])
edu_df = pd.DataFrame(Edu_details, columns= ["Student1", "Student2","Student3"], index =["Name", "age", "School"])
edu_df

       Student1 Student2 Student3
Name    Mustufa    Ahmed  Ibrahim
age          21       19       12
School      ABA      AUS      ASD

In [5]:
df[df["Name"].str.contains("Mustufa")]

             Name  Age School
Person 1  Mustufa   21    ABA

In [6]:
countries = pd.read_csv("./Data/Countries.csv", sep=",")

In [7]:
countries

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

##### Selection and Indexing of Columns

In [8]:
df2 = pd.DataFrame({"Name":["John","Anna","Peter","Linda"], "Age":[28,32,29,42], "City":["New York", "Paris", "Berlin", "London"], "Salary":[65000,70000, 62000, 85000]})
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [10]:
df2.iloc[:,0]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [11]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   32
2  Peter   29
3  Linda   42

##### Creating a new column

In [12]:
df2["Designation"] = ["Doctor","Engineer","Doctor","Engineer"]

In [13]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   32     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [14]:
df2.drop(columns=(["Name"]))
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   32     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [15]:
df2.drop(0,axis=0, inplace=True)
df2

    Name  Age    City  Salary Designation
1   Anna   32   Paris   70000    Engineer
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000    Engineer

In [16]:
df2.drop("Age",axis=1,inplace=True)
df2

    Name    City  Salary Designation
1   Anna   Paris   70000    Engineer
2  Peter  Berlin   62000      Doctor
3  Linda  London   85000    Engineer

In [17]:
df2.drop(columns=["Name","Salary"],inplace =True)
df2

     City Designation
1   Paris    Engineer
2  Berlin      Doctor
3  London    Engineer

#### Selecting Rows

In [18]:
df3 = pd.DataFrame({"Name":["John","Anna","Peter","Linda"], "Age":[28,32,29,42], "City":["New York", "Paris", "Berlin", "London"], "Salary":[65000,70000, 62000, 85000]})

In [19]:
df3.loc[0,:]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [20]:
df3.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [21]:
df3.loc[[0,1],:]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   32     Paris   70000

In [22]:
df3.iloc[[0,1],[0,1]]

   Name  Age
0  John   28
1  Anna   32

Selecting subsets of Rows and Columns

In [23]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df3.iloc[0:2,2:] #Don't put slices inside Brackets

       City  Salary
0  New York   65000
1     Paris   70000

In [25]:
df3.loc[[2,3],["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [26]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df3.loc[df3["Age"]>30]

    Name  Age    City  Salary
1   Anna   32   Paris   70000
3  Linda   42  London   85000

In [28]:
df3[df3["Age"]>30][["City","Salary"]]

     City  Salary
1   Paris   70000
3  London   85000

In [29]:
#I only want people that have the age greater than 30 and are from paris

df3[(df3["Age"]>30) & (df3["City"] == "Paris")] # REMEMBER: Must be in parenthisis

   Name  Age   City  Salary
1  Anna   32  Paris   70000

Missing DATA (v.imp)

In [30]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.isna() #Checks the table for NaN values

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [32]:
df.isna().sum() #Sum shows the axis = 0 each column and then add them according to column

A    1
B    0
C    2
D    3
dtype: int64

In [33]:
columns = df.isna().any() #Checks which columns have at least one null value and any is used for True or False (default, axis = 0)

Removing Missing Data

In [34]:
df #Works on basis of rows

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [35]:
df.dropna() # Drop is always based on rows (removes rows completely if they have na)

     A  B    C    D
0  1.0  1  1.0  1.0

In [36]:
df.dropna(thresh=3,axis = 0) #Dropna with the threshold of 3 looks for minimum 3 non null values and the remaining it will remove

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [37]:
df.dropna(thresh=4,axis = 0) #Dropna will know find rows that have at least 4 non null values

     A  B    C    D
0  1.0  1  1.0  1.0

Filling the missing values

In [38]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [39]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [40]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [41]:
values ={"A":0,"B":100,"C":300, "D":400}
df.fillna(value = values) #fillna happens on columns and not rows

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [42]:
mean_a = df["A"].mean()
mean_b = df["B"].mean()
mean_c = df["C"].mean()
mean_d = df["D"].mean()
i = {"A":mean_a,"B":mean_b,"C":mean_c,"D":mean_d}
df.fillna(value=i) #Fills based on columns

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [43]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [44]:
r = df.mean()
z = r.items()

for x,y in z:
  print(x,y)

A 3.0
B 3.0
C 2.0
D 3.0

In [45]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [46]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [47]:
df.isna().any(axis=0) # any is aggregation function (any, mean, sum, max, min)

A     True
B    False
C     True
D     True
dtype: bool

Merging/Joining/Concatenation

In [48]:
import pandas as pd
import numpy as np

In [49]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [50]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [51]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [52]:
pd.merge(employees,salaries, on="employee_id", how = "outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [53]:
pd.merge(employees,salaries, on="employee_id", how = "left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [54]:
pd.merge(employees,salaries, on="employee_id", how = "right").reset_index(drop=True)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**Concatination of 2 dataframes**

In [55]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [56]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [57]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [58]:
pd.concat([df1,df2]).reset_index(drop=True)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5

In [59]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [60]:
def checkname(column):
  return len(column) == 4

employees[employees["name"].apply(checkname)]

   employee_id  name department
0            1  John         HR
1            2  Anna         IT

In [61]:
pd.concat([df1,df2]).reset_index(drop=True)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5

In [62]:
pd.concat([df1,df2],axis =1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [63]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [64]:
employees[employees["name"].str.len()==4]["department"].value_counts()

department
HR    1
IT    1
Name: count, dtype: int64

In [65]:
merged = pd.merge(employees, salaries, on =["employee_id"], how = "inner")

In [66]:
job = pd.concat([employees,salaries], axis=0)

job["salary"]= job["salary"].fillna(job["salary"].mean())

Joining of two data frames

In [67]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [68]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [69]:
df1.index

Index([1, 2, 3], dtype='int64')

In [70]:
df1.columns

Index(['name'], dtype='str')

In [71]:
df2.index

Index([2, 3, 4], dtype='int64')

In [72]:
df2.columns

Index(['score'], dtype='str')

In [ ]:
df1.join(df2) #default of how is left

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [77]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [78]:
df2

   score
2     85
3     90
4     75

Advanced Concatenation & merging

In [87]:
coffee = pd.read_csv("./Data/coffee.csv")
coffee.head()
pd.set_option("display.max_rows",20)

In [88]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [89]:
coffee[coffee["Coffee Type"].str.contains("Latte", case =False)]

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35

In [93]:
coffee.nunique()

Day            7
Coffee Type    2
Units Sold     7
dtype: int64

In [96]:
coffee.shape

(14, 3)

In [95]:
coffee.size

42

Groupby and Aggregation

In [102]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [103]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [115]:
df.groupby("Category")["Quantity"].mean()

Category
A    11.25
B    19.50
Name: Quantity, dtype: float64

In [ ]:
df[df["Category"] == "A"][["Quantity"]].sum() #Took rows of Categories that are A and the quantity column of the  and the sum of them

Quantity    45
dtype: int64

In [120]:
df[df["Category"] == "A"]["Quantity"]

0    10
2    12
4     8
6    15
Name: Quantity, dtype: int64

Aggregation

In [121]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [131]:
grouped = df.groupby("Store")[["Quantity","Sales"]].agg(["sum","mean"])

In [132]:
grouped

      Quantity        Sales
           sum   mean   sum   mean
Store
S1          58  14.50   720  180.0
S2          65  16.25   780  195.0

In [133]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  8 non-null      str
 1   Store     8 non-null      str
 2   Sales     8 non-null      int64
 3   Quantity  8 non-null      int64
 4   Date      8 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 452.0 bytes

In [138]:
df["Date"] = df["Date"].astype(str)

In [139]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  8 non-null      str
 1   Store     8 non-null      str
 2   Sales     8 non-null      int64
 3   Quantity  8 non-null      int64
 4   Date      8 non-null      str
dtypes: int64(2), str(3)
memory usage: 452.0 bytes

In [156]:
df["Date"] = pd.to_datetime(df["Date"], format ="%y-%m-%d", errors = "coerce")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  8 non-null      str
 1   Store     8 non-null      str
 2   Sales     8 non-null      int64
 3   Quantity  8 non-null      int64
 4   Date      8 non-null      datetime64[us]
 5   Day       8 non-null      int32
dtypes: datetime64[us](1), int32(1), int64(2), str(2)
memory usage: 484.0 bytes

In [147]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [154]:
df["Day"] = df["Date"].dt.day

  Category Store  Sales  Quantity       Date  Day
0        A    S1    100        10 2023-01-01    1
1        B    S1    200        15 2023-01-02    2
2        A    S2    150        12 2023-01-03    3
3        B    S2    250        18 2023-01-04    4
4        A    S1    120         8 2023-01-05    5
5        B    S2    180        20 2023-01-06    6
6        A    S2    200        15 2023-01-07    7
7        B    S1    300        25 2023-01-08    8

!!! Aggregation & Groupby !!!

<small> Group by category and calculate the sum of sales </small>