In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.5'

In [4]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : e68db09ecf6427d1b62e565bacf17f2e525a3032
python                : 3.14.6
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 3.0.5
numpy                 : 2.5.2
dateutil              : 2.9.0.post0
pip                   : 26.1.2
Cython                : None
sphinx                : None
IPython               : 9.16.1
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyiceberg             : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
qtpy                  : None
pyqt5                 : None

In [5]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index = labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [6]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [7]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [8]:
df[["animal","age"]]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [9]:
df.iloc[[2,3,7],[0,1]]

  animal  age
c  snake  0.5
d    dog  NaN
h    cat  NaN

In [10]:
df[df["visits"]>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [11]:
df[df["age"].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [12]:
df[(df["animal"]=="cat") & (df["age"]<3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [13]:
df[(df["age"]>2) & (df["age"]<=4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no

In [14]:
df.loc["f","age"] = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [15]:
df["visits"].sum()

np.int64(19)

In [16]:
df["age"].mean()

np.float64(3.375)

In [17]:
df.loc["k"] = ["snake",3.0,1,"no"]

In [18]:
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k  snake  3.0       1       no

In [19]:
df.drop("k", axis = 0, inplace = True)

In [20]:
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [21]:
df["animal"].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

In [22]:
df.sort_values(["age"], ascending=False)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
b    cat  3.0       3      yes
j    dog  3.0       1       no
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [23]:
df.sort_values(["age","visits"], ascending=[0,1])

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

In [24]:
df["priority"] = df["priority"].apply(lambda x: x.strip().lower() == "yes")

In [25]:
df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

In [26]:
def cut(txt):
  data =""
  for x in range(len(txt)):
    if txt[x] == "(":
      for y in range(x+1,x+7):
        data+= txt[y]
    return data

sen = "My name is mustufa (age 24)"
cut(sen)

''

In [27]:
def adding(): 
  z = 0
  for x in range(10):
    z +=1
  
  return z

print(adding())

10

In [28]:
df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

In [29]:
df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

In [38]:
df.to_string()

'  animal  age  visits  priority\na    cat  2.5       1      True\nb    cat  3.0       3      True\nc  snake  0.5       2     False\nd    dog  NaN       3      True\ne    dog  5.0       2     False\nf    cat  1.5       3     False\ng  snake  4.5       1     False\nh    cat  NaN       1      True\ni    dog  7.0       2     False\nj    dog  3.0       1     False'

In [50]:
df.dropna(thresh=4,inplace = True)
df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
i    dog  7.0       2     False
j    dog  3.0       1     False

In [58]:
df.drop_duplicates(subset=["animal","visits"], keep="first")

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
e    dog  5.0       2     False
g  snake  4.5       1     False
j    dog  3.0       1     False

In [56]:
df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
i    dog  7.0       2     False
j    dog  3.0       1     False

In [60]:
df.duplicated()

a    False
b    False
c    False
e    False
f    False
g    False
i    False
j    False
dtype: bool

In [62]:
list (df.shape)

[8, 4]